//
//  REAlbumCover.h
//  soul-sifter
//
//  Created by Robby Neale
//  Generated by generate_model.rb
//

#ifndef __soul_sifter__REAlbumCover__
#define __soul_sifter__REAlbumCover__

#include <set>
#include <string>
#include <vector>

#include "ResultSetIterator.h"

namespace sql {
    class ResultSet;
}

using namespace std;

namespace dogatech {
namespace soulsifter {


    class REAlbumCover {
    public:
        REAlbumCover();
        explicit REAlbumCover(const REAlbumCover& reAlbumCover);
        void operator=(const REAlbumCover& reAlbumCover);
        ~REAlbumCover();
        void clear();

        static REAlbumCover* findById(int id);
        static REAlbumCover* findByREId(const string& reId);
        static ResultSetIterator<REAlbumCover>* findAll();

        int update();
        int save();
        // sync with db & return true if object needs saving or updating
        bool sync();

        const int getId() const;
        void setId(int id);
        const string& getREId() const;
        void setREId(const string& reId);
        const string& getThumbnail() const;
        void setThumbnail(const string& thumbnail);

        friend ResultSetIterator<REAlbumCover>;
        friend class SearchUtil;

    private:
        int id;
        string reId;
        string thumbnail;

        static void populateFields(const sql::ResultSet* rs, REAlbumCover* reAlbumCover);
    };

}
}

#endif /* defined(__soul_sifter__REAlbumCover__) */
