//
//  RESetting.h
//  soul-sifter
//
//  Created by Robby Neale
//  Generated by generate_model.rb
//

#ifndef __soul_sifter__RESetting__
#define __soul_sifter__RESetting__

#include <set>
#include <string>
#include <vector>

#include "ResultSetIterator.h"

namespace sql {
    class ResultSet;
}

using namespace std;

namespace dogatech {
namespace soulsifter {


    class RESetting {
    public:
        RESetting();
        explicit RESetting(const RESetting& reSetting);
        void operator=(const RESetting& reSetting);
        ~RESetting();
        void clear();

        static RESetting* findById(int id);
        static RESetting* findByName(const string& name);
        static ResultSetIterator<RESetting>* findAll();

        int update();
        int save();
        // sync with db & return true if object needs saving or updating
        bool sync();

        static void findAll(vector<const RESetting*>* settings);

        string& getValueRef();

        const int getId() const;
        void setId(int id);
        const string& getName() const;
        void setName(const string& name);
        const string& getValue() const;
        void setValue(const string& value);

        friend ResultSetIterator<RESetting>;
        friend class SearchUtil;

    private:
        int id;
        string name;
        string value;

        static void populateFields(const sql::ResultSet* rs, RESetting* reSetting);
    };

}
}

#endif /* defined(__soul_sifter__RESetting__) */
